version: '3.7'

services:
  
  # bot:
  #   build: .
  #   container_name: telegram_bot
  #   depends_on:
  #     - db

  db:
    image: "postgres:12.18-alpine3.18"
    container_name: postgres-py
    restart: always
    ports:
      - "8001:5432"
    shm_size: 128mb
    env_file:
      - .env